---
- name: Inspect AAP execution environment
  hosts: all

  tasks:
    - name: Display hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: Display Python interpreter
      ansible.builtin.debug:
        var: ansible_python_interpreter

    - name: Display operating system
      ansible.builtin.debug:
        var: ansible_distribution
